create table seat
(
    hall_id         integer,
    seat_id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    row_number      integer,
    seat_number     integer,

    foreign key(hall_id) references hall(id) ON DELETE CASCADE,
    CONSTRAINT pk_seat PRIMARY KEY (hall_id, seat_id)
);