ALTER TABLE seat ADD CONSTRAINT unique_seat_id UNIQUE (seat_id);

create table ticket (
    ticket_id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    payin_time     TIMESTAMP NOT NULL,
    total          float not null,
    status         varchar(32) not null,
    total_seats    int NOT NULL,
    member_id      BIGINT not null,

    CONSTRAINT pk_ticket PRIMARY KEY (ticket_id),
    FOREIGN KEY (member_id) REFERENCES members (id) ON UPDATE CASCADE
);

create table ticket_items (
    ticket_id           BIGINT NOT NULL,
    item_id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    project_id          BIGINT NOT NULL,
    seat_id             BIGINT NOT NULL,

    PRIMARY KEY (ticket_id, item_id),
    FOREIGN KEY (seat_id) REFERENCES seat(seat_id),
    FOREIGN KEY (project_id) REFERENCES projects(project_id)
);
