create table roles (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    movie_id       BIGINT,
    actor_id       BIGINT,
    role_name      varchar(255),

    CONSTRAINT pk_role PRIMARY KEY (id)
)