create table hall (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    hall_name      varchar(12),
    rows_count     int,
    seats_per_row  int,

    CONSTRAINT pk_hall PRIMARY KEY (id)
)