create table projects (
    project_id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    movie_id                 BIGINT NOT NULL,
    hall_id                  BIGINT NOT NULL,
    time                     TIME NOT NULL,

    CONSTRAINT pk_project PRIMARY KEY (project_id),
    FOREIGN KEY (movie_id) REFERENCES movie (id) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (hall_id) REFERENCES hall (id) ON DELETE CASCADE ON UPDATE CASCADE
)