create table broadcast (
    broadcast_id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    movie_id                 BIGINT NOT NULL,
    hall_id                  BIGINT NOT NULL,
    time                     TIME NOT NULL,

    CONSTRAINT pk_broadcast PRIMARY KEY (broadcast_id, movie_id, hall_id),
    FOREIGN KEY (movie_id) REFERENCES movie (id),
    FOREIGN KEY (hall_id) REFERENCES hall (id)
)